# Example of xrayhelper config
xrayHelper:
    # Required, Default value: xray
    coreType: xray
    # Required, absolute path to your core
    corePath: /data/adb/xray/bin/xray
    # Required, absolute path to your core config, can be a directory or single file
    coreConfig: /data/adb/xray/confs/
    # Required, absolute path to xrayhelper data directory, include a lot of data of xrayhelper
    # such as core geodata
    dataDir: /data/adb/xray/data/
    # Required, absolute path to xrayhelper temp directory, include xrayhelper logs, core pid, core logs and so on
    runDir: /data/adb/xray/run/
proxy:
    # Required, Default value: tproxy
    method: tproxy
    # Required for tproxy, Default value: 65535, port of core tproxy inbound
    tproxyPort: 65535
    # Required, Default value: false, enable ipv6 proxy, need your proxy server support proxy ipv6 traffic
    enableIPv6: false
    # Required, Default value: blacklist, application package list proxy mode, support blacklist, whitelist
    # blacklist mode, application traffic in pkgList will be bypassed, others will be marked
    # whitelist mode, application traffic in pkgList will be marked, others will be bypassed
    # Special, if pkgList is empty, all application traffic will be marked whatever which proxy mode you use
    mode: whitelist
    # Optional, application package list, format is "apk_package_name:user", the apk_package_name support wildcard matching, if the user value is omitted, it will be "0", aka the phone owner
    pkgList:
        - com.termux
    # Optional, ap interface list, external traffic from apList will be marked
    apList:
        - wlan2
        - rndis0
    # Optional, ignore interface list, internal traffic from ignoreList will be bypassed
    ignoreList:
        - wlan+
    # Optional, intranet CIDR address list, by default, most intranet ip will be bypassed, add CIDR address to intraList if you want mark these traffic
    intraList:
        - 192.168.123.0/24
        - fd12:3456:789a:bcde::/64
